spring.application.name=e-commerce
server.port=8080
spring.mongodb.uri=mongodb+srv://Krishu:DarkKnight5@krishu0.u1cluzl.mongodb.net/?appName=Krishu0
spring.mongodb.database=ecommerce2
jwt.secret=${JWT_SECRET}
